// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lz76_complexity
double lz76_complexity(NumericVector v);
RcppExport SEXP _randMeasures_lz76_complexity(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(lz76_complexity(v));
    return rcpp_result_gen;
END_RCPP
}
// SWLZ_lengths
NumericVector SWLZ_lengths(NumericVector x);
RcppExport SEXP _randMeasures_SWLZ_lengths(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(SWLZ_lengths(x));
    return rcpp_result_gen;
END_RCPP
}
// SWLZ_ER
double SWLZ_ER(NumericVector sequence);
RcppExport SEXP _randMeasures_SWLZ_ER(SEXP sequenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type sequence(sequenceSEXP);
    rcpp_result_gen = Rcpp::wrap(SWLZ_ER(sequence));
    return rcpp_result_gen;
END_RCPP
}
// block_entropy
double block_entropy(NumericVector x, int block_size);
RcppExport SEXP _randMeasures_block_entropy(SEXP xSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(block_entropy(x, block_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_randMeasures_lz76_complexity", (DL_FUNC) &_randMeasures_lz76_complexity, 1},
    {"_randMeasures_SWLZ_lengths", (DL_FUNC) &_randMeasures_SWLZ_lengths, 1},
    {"_randMeasures_SWLZ_ER", (DL_FUNC) &_randMeasures_SWLZ_ER, 1},
    {"_randMeasures_block_entropy", (DL_FUNC) &_randMeasures_block_entropy, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_randMeasures(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
