# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Lempel-Ziv complexity as implemented in Angelike & Musch, 2024
#'
#' @param v sequence
#' @export
lz76_complexity <- function(v) {
    .Call(`_randMeasures_lz76_complexity`, v)
}

SWLZ_lengths <- function(x) {
    .Call(`_randMeasures_SWLZ_lengths`, x)
}

#' Calculate Lempel-Ziv entropy rate using sliding window method (Vegetabile et al., 2019)
#'
#' @param sequence sequence
#' @export
SWLZ_ER <- function(sequence) {
    .Call(`_randMeasures_SWLZ_ER`, sequence)
}

