# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SWLZ_lengths <- function(x) {
    .Call(`_randMeasures_SWLZ_lengths`, x)
}

#' Calculate Lempel-Ziv entropy rate using sliding window method (Vegetabile et al., 2019)
#'
#' @param sequence
#' @export
SWLZ_ER <- function(sequence) {
    .Call(`_randMeasures_SWLZ_ER`, sequence)
}

