# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Lempel-Ziv complexity as implemented in Angelike & Musch, 2024
#'
#' @param v sequence
#' @export
lz76_complexity <- function(v) {
    .Call(`_randMeasures_lz76_complexity`, v)
}

#'Recurrent Quantification Analyses
#'
#'@param sequence sequence to analyse
#'@param lmin minimum diagonal length for DET
#'@param vmin minimum vertical length for LAM
#'@return list of RQA results
#' @export
RQA <- function(sequence, lmin = 2L, vmin = 2L) {
    .Call(`_randMeasures_RQA`, sequence, lmin, vmin)
}

SWLZ_lengths <- function(x) {
    .Call(`_randMeasures_SWLZ_lengths`, x)
}

#' Calculate Lempel-Ziv entropy rate using sliding window method (Vegetabile et al., 2019)
#'
#' @param sequence sequence
#' @export
SWLZ_ER <- function(sequence) {
    .Call(`_randMeasures_SWLZ_ER`, sequence)
}

#' Calculate block entropy (as in randfindR package)
#' @param x sequence
#' @param block_size length of blocks in which the original sequence should be divided for analysis
#' @export
block_entropy <- function(x, block_size = 1L) {
    .Call(`_randMeasures_block_entropy`, x, block_size)
}

phi_index_cpp <- function(seq, minScale, maxScale, maxOrder, list_options) {
    .Call(`_randMeasures_phi_index_cpp`, seq, minScale, maxScale, maxOrder, list_options)
}

